import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {snakePreview} from './draft-setup.mjs';
const db=await PGlite.create(), q=async(s,p=[])=>(await db.query(s,p)).rows;
try {
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select null::uuid$$;`);
 const dir=new URL('../migrations/',import.meta.url);
 for(const f of (await readdir(dir)).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL(f,dir),'utf8'));
 const user='00000000-0000-0000-0000-000000000001';
 await q('insert into auth.users values($1)',[user]);
 await q("insert into draft.owner_accounts select $1,id from draft.owners where slug='doug'",[user]);
 await q("insert into draft.league_roles values($1,'commissioner')",[user]);
 const original=await q('select slug,display_name name from draft.owners order by slug');
 const points=n=>Array.from({length:n},(_,i)=>(n-1-i)*10);
 const configure=(members,values=points(members.length),actor=user)=>q('select draft.configure_membership(2027,$1,$2,$3)',[JSON.stringify(members),values,actor]);
 await assert.rejects(()=>configure(original,points(9),'00000000-0000-0000-0000-000000000002'),/commissioner/);
 await assert.rejects(()=>configure([...original,original[0]]),/Unique members/);
 await assert.rejects(()=>configure(original,[100,90]),/placement table/);
 await assert.rejects(()=>configure(original,Array(9).fill(10)),/placement table/);
 await q(`select trading.import_pick_ledger(' {"version":1,"trades":[]} '::jsonb)`);
 const ten=[...original,{slug:'expansion',name:'Expansion'}];
 await configure(ten);
 const expansionDraft=(await q("insert into draft.drafts(name,kind,championship_year,rounds,participant_count) values('Expansion','startup',2027,65,10) returning id"))[0].id;
 await q('insert into draft.draft_participants select $1,id,row_number() over(order by slug) from draft.owners where active',[expansionDraft]);
 assert.equal((await q('select draft.generate_snake_picks($1) n',[expansionDraft]))[0].n,650);
 await q("update draft.drafts set status='cancelled' where id=$1",[expansionDraft]);
 assert.equal((await q('select count(*)::int n from draft.owners where active'))[0].n,10);
 assert.equal((await q('select count(*)::int n from trading.picks'))[0].n,200);
 const preview=snakePreview(ten.map(o=>o.slug));assert.equal(preview.length,650);assert.equal(preview[9].owner,preview[10].owner);
 await q("select trading.ingest_rosters('NFL','fixture',clock_timestamp(),$1)",[JSON.stringify(ten.map(o=>({owner:o.slug,players:[]})))]);
 await assert.rejects(()=>q("select trading.ingest_rosters('NFL','fixture',clock_timestamp(),$1)",[JSON.stringify(original.map(o=>({owner:o.slug,players:[]})))]),/active-owner/);
 await configure(original.slice(0,8));
 assert.equal((await q('select count(*)::int n from trading.picks'))[0].n,160);
 assert.equal((await q('select count(*)::int n from draft.owners'))[0].n,10);
 assert.equal(snakePreview(original.slice(0,8).map(o=>o.slug)).length,520);
 console.log('PASS 10-owner expansion, 8-owner contraction, retained identities, exact roster completeness and rookie picks');
 await configure(original);
 const pick=(await q("select p.id from trading.picks p join draft.owners o on o.id=p.original_owner_id where o.slug='tucker' limit 1"))[0].id;
 await q("update trading.picks set owner_id=(select id from draft.owners where slug='doug') where id=$1",[pick]);
 await assert.rejects(()=>configure(original.slice(0,8)),/Resolve roster/);
 assert.equal((await q('select count(*)::int n from draft.owners where active'))[0].n,9);
 const d=(await q("insert into draft.drafts(name,kind,championship_year,rounds,participant_count) values('guard','startup',2027,65,9) returning id"))[0].id;
 await assert.rejects(()=>configure(ten),/Cancel unused/);
 await q("insert into draft.draft_participants select $1,id,row_number() over(order by slug) from draft.owners where active",[d]);
 await q("select draft.generate_snake_picks($1)",[d]);
 await q("update draft.drafts set status='cancelled',current_pick_number=1 where id=$1",[d]);
 await assert.rejects(()=>configure(ten),/started or completed/);
 await db.exec('set role authenticated');
 await assert.rejects(()=>q('select * from draft.season_settings'),/permission denied/);
 await assert.rejects(()=>configure(ten),/permission denied/);
 await db.exec('reset role');
 console.log('PASS unauthorized access, invalid points, traded asset removal and started/cancelled draft protection');
} finally {await db.close();}

